### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by simonkowallik** [aidanhs/tclscan#2]
It would be great to see a license for `tclscan` to clarify permissions of use, limitations and conditions. According to [GitHub's Terms of Serivce](https://help.github.com/en/articles/github-terms-of-service#d-user-generated-content) forking of your repository is allowed but that's about it.

References:
- [GitHub : Help: Choosing the right license](https://help.github.com/en/articles/licensing-a-repository#choosing-the-right-license)
- [What can I assume if a publicly published project has no license?](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license)
- [choosealicense.com](https://choosealicense.com/)

**Comment by aidanhs** [comment]
Thanks for the poke - I'll license under MIT. I should've checked with #1 before merging, if I don't get a response in a few weeks I'll revert and add the license file.

**Comment by kugg** [comment]
All good here! MIT is fine by me.
This being said @aidanhs you are the author of this software and are entitled to license it as you see fit.

**Comment by aidanhs** [comment]
License and readme added, thanks!

(@kugg it's true, but it's generally accepted that if someone has made non-trivial contributions like yourself then you have to get permission from them as well - which you have given, so all is good)
